config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'lists#index'
  resources :lists, only: [:show, :new, :create] do
    resources :bookmarks, only: [:create, :destroy]
    resources :reviews, only: [:create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :comment, length: { minimum: 6 }
  validates :movie_id, uniqueness: { scope: :list_id }
end

app/models/list.rb
class List < ApplicationRecord
  has_one_attached :photo
  has_many :reviews
  has_many :bookmarks
  has_many :movies, through: :bookmarks, dependent: :destroy
  validates :name, uniqueness: true
  validates :name, presence: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, uniqueness: true
  validates :title, presence: true
  validates :overview, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :list
  validates :comment, presence: true
  validates :rating, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @list = List.find(params[:list_id])
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list) # checker redict
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id, :list_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
    @search = params[:query]
    if @search.present?
      @lists = List.where("name LIKE '%#{@search}%'")
    end
  end

  def show
    @list = List.find(params[:id])
    @movies = @list.movies
    @bookmark = Bookmark.new
    @review = Review.new
    @reviews = @list.reviews
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  private

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def create
    @review = Review.new(review_params)
    @list = List.find(params[:list_id])
    @review.list = @list
    if @review.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  private

  def review_params
    params.require(:review).permit(:comment, :rating, :list_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/bookmarks/new.html.erb
<h1>Create a new bookmark</h1>

<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.input :comment %>
  <%= f.association :movie %>
  <%= f.button :submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render "layouts/shared/navbar" %>
    <%= yield %>
    <%= render "layouts/shared/footer" %>
  </body>
</html>

app/views/layouts/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="https://www.instagram.com/chenchen_hamster/?hl=fr"><i class="fab fa-instagram"></i></a>
    <a href="https://github.com/ChenchenZheng"><i class="fab fa-github"></i></a>
    <a href="https://www.linkedin.com/in/chenchen-zheng/"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This footer is made by Chenchen with <i class="fas fa-heart"></i> at Le Wagon
  </div>
</div>

app/views/layouts/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-transparent navbar-light navbar-theme-primary">
  <div class="d-flex justify-content-between align-items-baseline">
    <div><%= link_to "Chenchen's list", root_path, class:"nav-link" %></div>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <%= form_tag root_path, class: 'd-flex', method: :get do %>
          <%= text_field_tag :query, params[:query], class: "form-control mr-2", placeholder: "Find a list"%>
          <%= submit_tag "Search", class: "btn btn-primary text-dark mr-2 mb-2" %>
        <% end %>
        <%= link_to "New list", new_list_path, class:"btn btn-primary text-info mr-2 mb-2" %>
      </div>
    </div>
  </div>
</nav>

app/views/lists/index.html.erb
<div class="banner" style="background-image: linear-gradient(#f8f9fa00,rgb(0 0 0 / 15%)), url(https://images.unsplash.com/photo-1493804714600-6edb1cd93080?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1050&q=80);">
  <div class="container">
    <h1>The best ranking list ever!</h1>
    <p>We've prepared six lists of film, TV series and japanesse animes for you</p>
  </div>
</div>

<div class="container mt-5">
  <div class="row">
    <% @lists.each do |list| %>
      <div class="col-12 col-md-4 mb-5">
        <div class="card bg-primary border-light shadow-soft">
          <%= cl_image_tag list.photo.key, height: 300, width: 400, crop: :fill, class:"card-img-top rounded-top" %>
          <div class="card-body">
            <h5 class="card-title d-flex justify-content-center"><%= list.name %></h5>
            <%= link_to "", list_path(list), class:"stretched-link" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/lists/new.html.erb
<div class="container">
  <h1>Add a new list</h1>
  <div class="container mt-3">
    <%= simple_form_for @list do |f| %>
      <%= f.input :name %>
      <%= f.input :photo, as: :file %>
      <%= f.submit class:"btn btn-primary mt-2"%>
    <% end %>
  </div>
</div>

app/views/lists/show.html.erb
<div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cloudinary_url(@list.photo.key) %>')">
  <h2><%= @list.name %></h2>
</div>

<div class="container m-5">
  <div class="d-flex justify-content-center row">
    <% @movies.each do |movie| %>
      <div class="col-12 col-md-4 mb-5">
        <div class="card bg-primary border-light shadow-soft">
          <%= image_tag "#{movie.poster_url}", class:"card-img-top rounded-top" %>
          <div class="card-body">
            <h5 class="card-title"><%= movie.title %></h5>
            <p class="card-text"><%= movie.rating %> stars<i class="fas fa-star"></i></p>
            <p class="card-text"><%= movie.overview %></p>
            <i class="fas fa-quote-left"></i><%= Bookmark.find_by(list: @list, movie: movie).comment %></p>
            <%= link_to "Delete",
              list_bookmark_path(@list, Bookmark.find_by(list: @list, movie: movie)),
              method: :delete,
              class: "btn btn-primary text-danger mr-2 mb-2",
              data: { confirm: "Are you sure to delete this bookmark?" } %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

<div class="container m-5">
  <h2>If you want to create a new bookmark</h2>
  <%= simple_form_for [@list, @bookmark] do |f| %>
    <%= f.input :comment %>
    <%= f.association :movie %>
    <%= f.submit class:"btn btn-primary mt-2" %>
  <% end %>
</div>

<hr>

<div class="container m-5">
  <div class="row">
    <div class="col-6">
      <h2>All comments about this list (<%= @reviews.count %>)</h2>
      <% @reviews.each do |review| %>
        <p><%= review.comment %></p>
        <% (review.rating).times do |x| %>
          <i class="fas fa-star mb-5"></i>
        <% end %>
      <% end %>
    </div>

    <div class="col-6">
      <h2>Share your reviews of this list</h2>
      <%= simple_form_for [@list, @review] do |f| %>
        <%= f.input :comment %>
        <%= f.input :rating, collection: (1..5).to_a, label: "Rate this list", id:"review_rating" %>
        <%= f.submit class:"btn btn-primary mt-2" %>
      <% end %>
    </div>
  </div>
</div>